name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # every sunday at 14:00 UTC
    - cron: "0 14 * * SUN"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge

      - name: Add path DLL to windows path (windows only)
        runs-on: windows-latest
        run: echo "##[add-path]C:\Miniconda\Library\bin"

      - name: Install Dependencies
        run: |
          conda env update -f environment.yml -n base
          pip install -r requirements-dev.txt
          conda info -a

      - name: Lint python (ubuntu only)
        runs-on: ubuntu-latest
        run: black --check .

      - name: Lint (ubuntu only)
        runs-on: ubuntu-latest
        uses: docker://github/super-linter:v2.2.0

      - name: Test
        run: |
          cp README.md docs/index.md
          python -m pytest --cov-report term-missing --color=yes --cov=pyomeca tests

      - name: Coverage (ubuntu only)
        runs-on: ubuntu-latest
        env:
          COVERALLS_REPO_TOKEN: XiFSzZ4JyITqinzFkJhNKD201jE7Bilmh
        run: |
          pip install coveralls
          coveralls
